dist: xenial
language: python
python: [3.7, 3.8]
services:
  # required services for testing GUI
  - xvfb
install:
  - pip install -r requirements.txt
script:
  - make tests-no-gui
after_success:
  - coveralls
